name: learn-github-actions
on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@main
        with:
          node-version: '15.x'
      - name: Install dependency
        run: |
          yarn install
      - name: Setup Authors
        run: |
          git config --global user.name "$env:github.actor"
      - name: Build
        shell: powershell
        run: |
          yarn build

  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v